### ISSUE TITLE
Can you please add a license?

### ISSUE THREAD

**Issue by johanneskastl** [ChaosInTheCRD/kube-lock#3]
...or did I just not find one?

**Comment by johanneskastl** [comment]
Thanks! That was quick... :-)

fixed in 7db2a1896d286ef12ab4f2fa32968fe802aa7ff1

**Comment by ChaosInTheCRD** [comment]
Ha no worries! Was pretty excited to get some issues in! Thanks for raising them! Not sure if you're a `krew` person but I am in the process of getting it added: https://github.com/kubernetes-sigs/krew-index/pull/3409. Then you'll be able to `krew install` and `kubectl lock lock/unlock` 😊. I know the `kubectl lock lock` command seems a bit janky / repetitive, but it'll do for no!
