### ISSUE TITLE
First release?

### ISSUE THREAD

**Issue by johanneskastl** [ChaosInTheCRD/kube-lock#4]
For packaging it would be nice to have a tag or release, even if this is 0.0.1... :-)

**Comment by ChaosInTheCRD** [comment]
There is now a `v0.0.4` 😄 Will ensure everything is under release tag from now on. https://github.com/ChaosInTheCRD/kube-lock/releases/tag/v0.0.4

**Comment by ChaosInTheCRD** [comment]
Going to close this one now 😄
